import { test, expect, type Page } from '@playwright/test';

test('Prompt creation (success)', async ({ page }: { page: Page }) => {
  const uniqueTitle = `E2E Prompt ${Date.now()}`;
  const content = 'Content generated by E2E';

  await page.goto('/new');
  await expect(page.getByPlaceholder('Título do prompt')).toBeVisible();
  await page.fill('input[name="title"]', uniqueTitle);
  await page.fill('textarea[name="content"]', content);
  await page.getByRole('button', { name: 'Salvar' }).click();

  await page.waitForSelector('text=Prompt criado com sucesso', {
    state: 'visible',
    timeout: 15000,
  });
});
